src/Entity/Trick.php
<?php

namespace App\Entity;

use App\Entity\Video;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TrickRepository")
 * @Vich\Uploadable
 * @UniqueEntity(fields={"name"}, message="Le nom proposé n'est plus disponible")
 */
class Trick
{
    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->updated_at = new \DateTime();
        $this->comments = new ArrayCollection();
        $this->pictures = new ArrayCollection();
        $this->videos = new ArrayCollection();
    }

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="trick")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="trick", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $comments;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="tricks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Picture", mappedBy="trick", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $pictures;

    /**
     * @Assert\All({
     *   @Assert\Image(mimeTypes="image/jpeg")
     * })
     */
    private $pictureFiles;

    /**
     * @var string
     */
    private $videoFile;
    
    /**
     * @ORM\OneToMany(targetEntity=Video::class, mappedBy="trick", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $videos;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @var string|null
     */
    private $mainFileName;

    /**
     * @Vich\UploadableField(mapping="trick_main", fileNameProperty="mainFileName")
     * @Assert\Image(mimeTypes="image/jpeg")
     * 
     * @var File|null
     */
    private $mainImageFile;

    //--------------------------------------------------------------------------

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->name);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setTrick($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getTrick() === $this) {
                $comment->setTrick(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPictureFiles()
    {
        return $this->pictureFiles;
    }

    /**
     * @param mixed $pictureFiles
     * @return Trick
     */
    public function setPictureFiles($pictureFiles): self
    {
        foreach ($pictureFiles as $pictureFile) {
            $picture = new Picture();
            $picture->setImageFile($pictureFile);
            $this->addPicture($picture);
        }
        $this->pictureFiles = $pictureFiles;
        return $this;
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function getPicture(): ?Picture
    {
        if ($this->pictures->isEmpty()) {
            return null;
        }
        return $this->pictures->first();
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setTrick($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->contains($picture)) {
            $this->pictures->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getTrick() === $this) {
                $picture->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Video[]
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): self
    {
        if (!$this->videos->contains($video)) {
            $this->videos[] = $video;
            $video->setTrick($this);
        }

        return $this;
    }

    public function removeVideo(Video $video): self
    {
        if ($this->videos->contains($video)) {
            $this->videos->removeElement($video);
            // set the owning side to null (unless already changed)
            if ($video->getTrick() === $this) {
                $video->setTrick(null);
            }
        }

        return $this;
    }

    public function getVideoFile()
    {
        return $this->videoFile;
    }

    public function setVideoFile($videoFile)
    {
        $video = new Video();
        $video->setLink($videoFile);
        $video->setTrick($this);
        $this->addVideo($video);
        $this->video = $video;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getMainFileName(): ?string
    {
        return $this->mainFileName;
    }

    /**
     * @param string|null $mainFileName
     * @return Trick
     */
    public function setMainFileName(?string $mainFileName): Trick
    {
        $this->mainFileName = $mainFileName;
        return $this;
    }

    /**
     * @return File|null
     */
    public function getMainImageFile(): ?File
    {
        return $this->mainImageFile;
    }

    /**
     * @param File|null $mainImageFile
     * @return Trick
     */
    public function setMainImageFile(?File $mainImageFile): Trick
    {
        $this->mainImageFile = $mainImageFile;

        if ($this->mainImageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTime('now');
        }

        return $this;
    }
    
}

src/Form/TrickType.php
<?php

namespace App\Form;

use App\Entity\Trick;
use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class TrickType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name',  TextType::class, [
                'required'  =>  true,
                'label'     =>  'Name',
                'attr'      =>  [
                    'placeholder' => 'Name...'
                ]
            ])

            ->add('description', TextareaType::class, [
                'required'  =>  false,
                'label'     =>  'Description',
                'attr'      =>  [
                    'placeholder' => 'Description...'
                ]
            ])

            ->add('category', EntityType::class, [
                'choice_label'  => 'name',
                'label'         => 'Category',
                'class'         => Category::class,
                
            ])

            ->add('pictureFiles', FileType::class, [
                'required'  =>  false,
                'multiple'  =>  true,
                'attr'      =>  [
                    'placeholder' => 'Pictures...'
                ]
            ])

            ->add('videoFile',  TextType::class, [
                'required'  =>  false,
                'label'     =>  'Video',
                'attr'      =>  [
                    'placeholder' => 'Video /embed/ link...'
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Trick::class,
            'translation_domain' => 'forms',
        ]);
    }
}

src/Controller/TrickController.php
<?php

namespace App\Controller;

use App\Entity\Trick;
use App\Entity\Comment;
use App\Form\CommentType;
use App\Form\MainPictureType;
use App\Repository\CommentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class TrickController extends AbstractController
{
    /**
     * @Route("/trick/{slug}-{id}", name="trick.show", requirements={"slug": "[a-z0-9\-]*"})
     * @param Trick $trick
     * @param string $slug
     * @return Response
     */
    public function trickShow( Trick $trick, string $slug, CommentRepository $commentRepository,
        EntityManagerInterface $manager, Request $request, ?UserInterface $user): Response 
    {
        if ($trick->getSlug() !== $slug) {
            return $this->redirectToRoute('trick.show', [
                    'id'    =>  $trick->getId(),
                    'slug'  =>  $trick->getSlug()
                ],
                301
            );
        }

        // Modification de l'image à la une
        $form1 = $this->createForm(MainPictureType::class, $trick);
        $form1->handleRequest($request);

        if ($form1->isSubmitted() && $form1->isValid()) 
        {
            $manager->flush();

            return $this->redirectToRoute('trick.show', [
                'slug' => $trick->getSlug(),
                'id' => $trick->getId(),
                'nbComments' => $nbComments,
            ]);
        }

        $comment = new Comment();
        $form2 = $this->createForm(CommentType::class, $comment);

        $form2->handleRequest($request);

        if ($form2->isSubmitted() && $form2->IsValid()) 
        {
            $comment->setCreatedAt(new \DateTime());
            $comment->setTrick($trick);
            $comment->setUser($user);

            $manager->persist($comment);
            $manager->flush();

            return $this->redirectToRoute('trick.show', [
                'slug' => $trick->getSlug(),
                'id' => $trick->getId(),
                'nbComments' => $nbComments,
            ]);
        }

        // Affichage de 3 commentaires 
        $nbComments = $commentRepository->countTrikComments($trick);
        $comments = $commentRepository->findPaginateComments($trick, 0, 3);

        $displayButton = true;
        if ($nbComments <= 3) {
            $displayButton = false;
        }

        if ($nbComments > 3) {$nbComments = 3;}

        return $this->render('trick/show.html.twig', [
            'trick'         =>  $trick,
            'comments'      =>  $comments,
            'form1'         =>  $form1->createView(),
            'form2'         =>  $form2->createView(),
            'current-menu'  =>  'tricks',
            'nbComments'    =>  $nbComments,
            'buttonMore'    =>  $displayButton,
            
        ]);
    }

    /**
     * @Route("/trick/comments/more/{id}/{nbComments}", name="comment.more")
     * 
     */
    public function commentMore(Trick $trick, int $nbComments, CommentRepository $commentRepository)
    {
       
        $nbTrickComments = $commentRepository->countTrikComments($trick);
        
        $comment = $commentRepository->findOnePaginateComment($trick, $nbComments);

        $nbComments++;
       
        $displayButton = true;
        if($nbTrickComments == $nbComments)
        {
            $displayButton = false;
        }

        return $this->render('trick/_comments.html.twig', [
            'trick'         =>  $trick,
            'comment'       =>  $comment,
            'nbComments'    =>  $nbComments,
            'buttonMore'    =>  $displayButton,
        ]);
    }
}

templates/trick/_comments.html.twig
    <div class="unCommentaire row justify-content-center mb-3">
        <div class="col-md-1">
            {% if comment.user.userPicture %}
                <img class="photoProfil" src="{{ vich_uploader_asset(comment.user) }}" alt="comment.user.username">
            {% else %}
                <img class="photoProfil" src="{{ '/media/tricks/empty.jpg' }}" alt="">
            {% endif %}
        </div>

        <div class="col-md-10 ml-2">
            <div class="ligne_date font-weight-bold">
                Le {{ comment.createdAt | date("m/d/Y à H:i") }}h
            </div>
            <div class="ligne_content text-justify mt-1">
                {{ comment.content | raw }}
            </div>
        </div>

    </div>
    {# button more #}
    <div class="show_more_comment_btn mx-auto mb-3 d-flex justify-content-center">
        {% if buttonMore %}
            <a id='pathToController' href="{{ path('comment.more', { 'id' : trick.id, 'nbComments' : nbComments }) }}">
                <img class="show_more_comment_btn" src="{{ asset('build/plus.png') }}" alt="Plus">
            </a>
        {% endif %}
    </div>
   

templates/trick/_tricks.html.twig
<section class="d-flex flex-row justify-content-center flex-wrap home_tricks" id="tricksDisplay" >
    {% for trick in tricks %}
        <div class="card text-white bg-secondary" id="BlocTrickToDelete">
            {% if trick.mainFileName %}
                    <img src="{{ vich_uploader_asset(trick, 'mainImageFile') }}" alt="{{ trick.name }}" alt="card-img-top" class="card-img-top"/>
            {% else %}
                    {% if trick.picture %}
                        <img src="{{ vich_uploader_asset(trick.picture, 'imageFile') }}" alt="{{ trick.name }}" class="card-img-top">
                    {% else %}
                        <img src="{{ '/media/tricks/empty.jpg' }}" alt="{{ trick.name }}" class="card-img-top">
                    {% endif %}
            {% endif %}
            <div class="card-body d-flex justify-content-between">
                <div class="card-title">
                    <a href="{{ path('trick.show', {slug:trick.slug, id:trick.id }) }}">{{ trick.name }}</a>
                </div>
                <div class="liens">
                    {% if app.user %}
                        <a href="{{ path('admin.trick.edit', {id : trick.id}) }}">
                            <i class="fas fa-pencil-alt mt-2"></i>
                        </a>
                        <form class="tricks_delete_form" method="post" action="">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="token" value="{{ csrf_token('delete' ~ trick.id) }}">
                            <button id="delete-trick-link" class="btn"><i class="fas fa-trash-alt"></i></button>
                            <span data-path="{{ path('admin.trick.delete', {id : trick.id}) }}"></span>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endfor %}
</section>
{% if button %}
    <div class="more-comment-button" id="button-more-comments">
        <div class="row">
            <div class="mx-auto">                   
                <a href="{{ path('tricks.index.more', {tricksDisplay : tricksDisplay}) }}">
                    <img class="icone_plus" src='{{ asset("build/plus.png") }}' alt="Plus">
                </a>
            </div>   
        </div>
    </div>     
{% endif %}

templates/trick/show.html.twig
{% extends 'base.html.twig' %}

{% block mainPicture %}
    {% include "pages/_mainPicture.html.twig" %}
{% endblock %}

{% block body %}
    <div class="show_page mx-auto" id="haut">
        {# Bouton affichage media #}
        <div class="btn-affichage-media">
            <a id="btn-affichage-media" class="btn btn-primary btn-affichage-media">Affichage media</a>
        </div>

        {# Photos et vidéos #}
        <div id="div-affichage-photos-videos">
            <div  class="d-flex flex-wrap justify-content-around align-items-center">
                {# Images #}
                {% if trick.pictures %} 
                    {% for picture in trick.pictures %}
                        <div class="edit_cards m-2">
                            <img class="edit_card_img show_picture" src="{{ vich_uploader_asset(picture, 'imageFile') }}" alt="image">
                        </div>
                    {% endfor %}
                {% endif %}

                {# Vidéos #}
                {% if trick.videos %}
                    {% for video in trick.videos %}
                        <div class="edit_cards m-2">
                            <iframe width="190" height="180" src="{{ video.link }}" frameborder="0" allowfullscreen></iframe>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>

        {# Description #}
        <div class="show_description mx-auto mt-3 mb-2 p-2 ">
            {{ trick.description | raw }}
        </div>

        {# Infos diverses #}
        <div class="show_div_info justify-content-center mx-auto">
            <div id="mel" class="show_info border rounded">
                <span>mis en ligne le : {{ trick.createdAt | date("m/d/Y") }}</span>
            </div>
            <div class="show_info border rounded">
                <span>modifié le : <br >{{ trick.updatedAt | date("m/d/Y") }}</span>
            </div>
            <div class="show_info border rounded">
                <span>Catégorie : <br >{{ trick.category.name}}</span>
            </div>
        </div>

        <div class="show_barre mx-auto"><hr></div>

        {# Formulaire de commentaires #}
        {% if app.user %}
            {{ form_start(form2, {'method': 'POST'}) }}
                <div class="show-display-comment-form d-flex flex-row justify-content-center mx-auto">
                    <div class="mr-2 w-75">
                        {{ form_row(form2.content) }}
                    </div>
                    <div> 
                        <button type'submit' class="btn btn-success w-100 ">Commenter</button>
                    </div>
                </div>
            {{ form_end(form2) }}

        <div class="show_barre mx-auto"><hr></div>
        {% endif %}
        
        {# Commentaires #}
        {% if comments %}
            <section id="section_commentaires" class="show_commentaires mx-auto">
                <div class="mb-2">
                    {% for comment in comments %}
                        <div class="unCommentaire row justify-content-center mb-3">
                            <div class="col-2 col-md-1">
                                {% if comment.user.userPicture %}
                                    <img class="photoProfil" src="{{ vich_uploader_asset(comment.user) }}" alt="comment.user.username">
                                {% else %}
                                    <img class="photoProfil" src="{{ '/media/tricks/empty.jpg' }}" alt="">
                                {% endif %}
                            </div>

                            <div class="col-10 col-md-10">
                                <div class="ligne_date font-weight-bold">
                                    Le {{ comment.createdAt | date("m/d/Y à H:i") }}h
                                </div>
                                <div class="ligne_content text-justify mt-1">
                                    {{ comment.content | raw }}
                                </div>
                            </div>

                        </div>
                    {% endfor %}
                </div>
                {# button more #}
                <div class="show_more_comment_btn mx-auto mb-3 d-flex justify-content-center">
                    {% if buttonMore %}
                        <a id='pathToController' href="{{ path('comment.more', { 'id' : trick.id, 'nbComments' : nbComments }) }}">
                            <img class="show_more_comment_btn" src="{{ asset('build/plus.png') }}" alt="Plus">
                        </a>
                    {% endif %}
                </div>
            </section>
        {% endif %}               
    </div>
{% endblock %}

{% block javascripts %}
{{ parent() }}
<script>
   
    // Gestion affichage des commentaires
    $(function () {
        $("#section_commentaires").on('click', ('#pathToController'), function(e) {
            e.preventDefault();
            var path = $("#pathToController").attr('href');
            jsonToken="";

            $.ajax({
                type: "POST",
                url: path,
                data: jsonToken,
                cache: false,
                contentType: false,
                processData: false,
                async: false,
                dataType: "html",
                error: function (err) {
                    console.error(err);
                },
                success: function (data) {
                    $('.show_more_comment_btn').remove();
                    $("#section_commentaires").append(data);
                },
                complete: function () {
                    console.log("Request finished.");
                }
            });
            
        });  
    })
</script>
{% endblock %}
 